/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.voting.system;

import java.awt.Color;

/**
 *
 * @author Zulu
 */
public class Exit_Page extends javax.swing.JFrame {
    int xmouse;
    int ymouse;
    /**
     * Creates new form Exit_Page
     */
    public Exit_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_message = new javax.swing.JPanel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        done = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_message.setBackground(new java.awt.Color(255, 255, 255));
        pnl_message.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 87, 154)));
        pnl_message.setForeground(new java.awt.Color(43, 87, 154));
        pnl_message.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_messageMouseDragged(evt);
            }
        });
        pnl_message.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_messageMousePressed(evt);
            }
        });

        lbl3.setBackground(new java.awt.Color(43, 87, 154));
        lbl3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lbl3.setForeground(new java.awt.Color(43, 87, 154));
        lbl3.setText("VOTED SUCCESSFULLY");

        lbl4.setBackground(new java.awt.Color(43, 87, 154));
        lbl4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lbl4.setForeground(new java.awt.Color(43, 87, 154));
        lbl4.setText("THANK YOU!");

        done.setBackground(new java.awt.Color(43, 87, 154));
        done.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        done.setForeground(new java.awt.Color(255, 255, 255));
        done.setText("FINISH");
        done.setBorder(null);
        done.setBorderPainted(false);
        done.setContentAreaFilled(false);
        done.setOpaque(true);
        done.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                doneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                doneMouseExited(evt);
            }
        });
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_messageLayout = new javax.swing.GroupLayout(pnl_message);
        pnl_message.setLayout(pnl_messageLayout);
        pnl_messageLayout.setHorizontalGroup(
            pnl_messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(done, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_messageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl4)
                .addGap(134, 134, 134))
            .addGroup(pnl_messageLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lbl3)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        pnl_messageLayout.setVerticalGroup(
            pnl_messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_messageLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lbl3)
                .addGap(18, 18, 18)
                .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(done, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnl_message, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void doneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneMouseEntered
        done.setOpaque(true);
        done.setBackground(new Color(255,203,49));
        done.setForeground(Color.black);
    }//GEN-LAST:event_doneMouseEntered

    private void doneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneMouseExited
        done.setOpaque(true);
        done.setBackground(new Color (43,87,154));
        done.setForeground(Color.white);
    }//GEN-LAST:event_doneMouseExited

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        new Voters_Log().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_doneActionPerformed

    private void pnl_messageMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_messageMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xmouse ,y - ymouse);
    }//GEN-LAST:event_pnl_messageMouseDragged

    private void pnl_messageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_messageMousePressed
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_pnl_messageMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exit_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exit_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exit_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exit_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Exit_Page().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton done;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JPanel pnl_message;
    // End of variables declaration//GEN-END:variables
}
