/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.voting.system;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Zulu
 */
public class Registration extends javax.swing.JFrame {
    int xmouse;
    int ymouse;
    Connection conn;
    Statement stmt;
    String url = ("jdbc:ucanaccess://D:\\SK Voting System\\Voting Database.accdb");
    /**
     * Creates new form RegsForm
     */
    public Registration() {
        initComponents();
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btng_sex = new javax.swing.ButtonGroup();
        pnl_register = new javax.swing.JPanel();
        lbl_FullName = new javax.swing.JLabel();
        txt_lname = new javax.swing.JTextField();
        lbl_residence = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        lbl_addFormat = new javax.swing.JLabel();
        lbl_datebirth = new javax.swing.JLabel();
        txt_PersoalInfo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbl_sex = new javax.swing.JLabel();
        lbl_contact = new javax.swing.JLabel();
        txt_contactNo = new javax.swing.JTextField();
        lbl_email = new javax.swing.JLabel();
        txt_emailAdd = new javax.swing.JTextField();
        lbl_age = new javax.swing.JLabel();
        rb_male = new javax.swing.JRadioButton();
        rb_female = new javax.swing.JRadioButton();
        txt_mname = new javax.swing.JTextField();
        txt_fname = new javax.swing.JTextField();
        lbl_name1 = new javax.swing.JLabel();
        lbl_name2 = new javax.swing.JLabel();
        lbl_name3 = new javax.swing.JLabel();
        drag = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        cb_age = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btn_submit = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        txt_pass1 = new javax.swing.JPasswordField();
        txt_pass2 = new javax.swing.JPasswordField();
        display = new javax.swing.JLabel();
        cb_month = new javax.swing.JComboBox<>();
        cb_year = new javax.swing.JComboBox<>();
        cb_date = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnl_register.setBackground(new java.awt.Color(255, 255, 255));
        pnl_register.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 47, 52)));
        pnl_register.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_FullName.setBackground(new java.awt.Color(0, 102, 102));
        lbl_FullName.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_FullName.setText("FULL NAME");
        pnl_register.add(lbl_FullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 94, -1, -1));

        txt_lname.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_lname.setForeground(new java.awt.Color(51, 51, 51));
        pnl_register.add(txt_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 119, 450, 32));

        lbl_residence.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_residence.setText("RESIDENCE/ADDRESS");
        pnl_register.add(lbl_residence, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 245, -1, -1));

        txt_address.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_address.setForeground(new java.awt.Color(51, 51, 51));
        pnl_register.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 275, 599, 32));

        lbl_addFormat.setBackground(new java.awt.Color(204, 204, 204));
        lbl_addFormat.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        lbl_addFormat.setText("House no./Street,  Barangay,  City/Municipality,  Province,  Region");
        pnl_register.add(lbl_addFormat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 318, -1, -1));

        lbl_datebirth.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_datebirth.setText("DATE OF BIRTH");
        pnl_register.add(lbl_datebirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 360, -1, -1));

        txt_PersoalInfo.setEditable(false);
        txt_PersoalInfo.setBackground(new java.awt.Color(102, 102, 102));
        txt_PersoalInfo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txt_PersoalInfo.setForeground(new java.awt.Color(255, 255, 255));
        txt_PersoalInfo.setText("       PART 1. PERSONAL INFORMATION");
        txt_PersoalInfo.setBorder(null);
        pnl_register.add(txt_PersoalInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, 37, 960, 32));
        pnl_register.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(961, 307, -1, -1));

        lbl_sex.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_sex.setText("SEX");
        pnl_register.add(lbl_sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(766, 94, -1, -1));

        lbl_contact.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_contact.setText("CONTACT NO.");
        pnl_register.add(lbl_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 355, -1, 28));

        txt_contactNo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_contactNo.setForeground(new java.awt.Color(51, 51, 51));
        pnl_register.add(txt_contactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 390, 250, 32));

        lbl_email.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_email.setText("EMAIL ADDRESS");
        pnl_register.add(lbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 452, -1, 28));

        txt_emailAdd.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_emailAdd.setForeground(new java.awt.Color(51, 51, 51));
        pnl_register.add(txt_emailAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 487, 350, 32));

        lbl_age.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_age.setText("AGE");
        pnl_register.add(lbl_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(766, 242, -1, -1));

        rb_male.setBackground(new java.awt.Color(255, 255, 255));
        btng_sex.add(rb_male);
        rb_male.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        rb_male.setText("Male");
        pnl_register.add(rb_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 120, -1, -1));

        rb_female.setBackground(new java.awt.Color(255, 255, 255));
        btng_sex.add(rb_female);
        rb_female.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        rb_female.setText("Female");
        pnl_register.add(rb_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 145, -1, -1));

        txt_mname.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_mname.setForeground(new java.awt.Color(51, 51, 51));
        pnl_register.add(txt_mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 195, 450, 32));

        txt_fname.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_fname.setForeground(new java.awt.Color(51, 51, 51));
        pnl_register.add(txt_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 157, 450, 32));

        lbl_name1.setBackground(new java.awt.Color(204, 204, 204));
        lbl_name1.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        lbl_name1.setText("Last Name");
        pnl_register.add(lbl_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 126, 86, -1));

        lbl_name2.setBackground(new java.awt.Color(204, 204, 204));
        lbl_name2.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        lbl_name2.setText("First Name");
        pnl_register.add(lbl_name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 164, 87, -1));

        lbl_name3.setBackground(new java.awt.Color(204, 204, 204));
        lbl_name3.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        lbl_name3.setText("Middle Name");
        pnl_register.add(lbl_name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 202, -1, -1));

        drag.setBackground(new java.awt.Color(43, 87, 154));
        drag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragMouseDragged(evt);
            }
        });
        drag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragMousePressed(evt);
            }
        });
        drag.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setBackground(new java.awt.Color(43, 87, 154));
        back.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("   Back to Admin  Menu  ");
        back.setBorder(null);
        back.setContentAreaFilled(false);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        back.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        back.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back.setOpaque(true);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        drag.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        pnl_register.add(drag, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 950, -1));

        cb_age.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        cb_age.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select your age", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        pnl_register.add(cb_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 272, -1, 29));

        jPanel1.setBackground(new java.awt.Color(43, 87, 154));

        btn_submit.setBackground(new java.awt.Color(255, 255, 255));
        btn_submit.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_submit.setText("SUBMIT");
        btn_submit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_submit.setContentAreaFilled(false);
        btn_submit.setOpaque(true);
        btn_submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_submitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_submitMouseExited(evt);
            }
        });
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        lbl1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        lbl1.setText("SETUP ACCOUNT");

        lbl3.setBackground(new java.awt.Color(255, 255, 255));
        lbl3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl3.setForeground(new java.awt.Color(255, 255, 255));
        lbl3.setText("Password");

        lbl4.setBackground(new java.awt.Color(255, 255, 255));
        lbl4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl4.setForeground(new java.awt.Color(255, 255, 255));
        lbl4.setText("Retype Password");

        lbl2.setBackground(new java.awt.Color(255, 255, 255));
        lbl2.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        lbl2.setForeground(new java.awt.Color(255, 255, 255));
        lbl2.setText("First Name will be your USERNAME.");

        txt_pass1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        txt_pass2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_pass2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pass2KeyReleased(evt);
            }
        });

        display.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl1)
                        .addGap(57, 57, 57))
                    .addComponent(lbl2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_pass2)
                    .addComponent(txt_pass1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(818, 818, 818))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(lbl2)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_pass1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl3)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_pass2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27))
                            .addComponent(btn_submit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );

        pnl_register.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 950, -1));

        cb_month.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        cb_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MONTH", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        pnl_register.add(cb_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 391, -1, 29));

        cb_year.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        cb_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YEAR", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004" }));
        pnl_register.add(cb_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 391, -1, 29));

        cb_date.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        cb_date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DATE", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        pnl_register.add(cb_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 391, -1, 29));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_register, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_register, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new Admin_Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setOpaque(true);
        back.setBackground(Color.RED);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setOpaque(false);
        back.setBackground(Color.BLACK);
    }//GEN-LAST:event_backMouseExited

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        String sex;
        String username = txt_fname.getText();
        String number = txt_contactNo.getText();
        String address = txt_address.getText();
        String i = (String)cb_age.getSelectedItem();
        String bday = ((String)cb_month.getSelectedItem()+" "+(String)cb_date.getSelectedItem()+" "+(String)cb_year.getSelectedItem());
        
        if(rb_male.isSelected()){
            sex = "Male";
        } else if (rb_female.isSelected()){
            sex = "Female";
        } else {
            sex = null;
        }
        
        if(txt_fname.getText().isEmpty() && txt_lname.getText().isEmpty() && txt_mname.getText().isEmpty() && address.isEmpty() && number.isEmpty() && bday.isEmpty() && txt_emailAdd.getText().isEmpty() && txt_pass1.getText().isEmpty() && txt_pass2.getText().isEmpty() 
                ||txt_fname.getText().isEmpty() || txt_lname.getText().isEmpty() || txt_mname.getText().isEmpty()||address.isEmpty()||number.isEmpty() || bday.isEmpty() || txt_emailAdd.getText().isEmpty() || txt_pass1.getText().isEmpty() || txt_pass2.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill ALL the fields! \n THANK YOU");
        }
        else if(sex == null){
            JOptionPane.showMessageDialog(null, "Select your SEX. \n THANK YOU");
        }
        else if(cb_month.getSelectedItem() == "MONTH" || cb_date.getSelectedItem() == "DATE" || cb_year.getSelectedItem() == "YEAR" || "MONTH DATE YEAR".equals(bday) ){
            JOptionPane.showMessageDialog(null, "Select your BIRTHDAY. \n THANK YOU");
        }
        else if(cb_age.getSelectedItem() == "Select your age"){
            JOptionPane.showMessageDialog(null, "Select your AGE. \n THANK YOU");
        }
        else{
            int age = Integer.parseInt(i);
            try{
                int contact = Integer.parseInt(number);
                String initial = Character.toString(txt_mname.getText().charAt(0));
                String fullname = (txt_lname.getText()+", "+txt_fname.getText()+" "+initial+".");
                
                conn = DriverManager.getConnection(url);
                stmt  = conn.createStatement();
                
                String query = ("INSERT INTO `Voters Information` (`Full Name`, `Address`, `Age`, `Sex`, `Username`, `Password`) VALUES ('"+fullname+"','"+address+"','"+age+"','"+sex+"','"+username+"','"+txt_pass2.getText()+"')");
                String query1 = ("INSERT INTO `Other Information` (`Full Name`, `Contact No`, `Email`, `Birthday`) VALUES ('"+fullname+"','"+contact+"','"+txt_emailAdd.getText()+"','"+bday+"')");
                stmt.executeUpdate(query);
                stmt.executeUpdate(query1);
                
                new Message_Box().setVisible(true);
                this.dispose();
                
            } catch(HeadlessException | SQLException | NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Checked your data again.");
                number = "";
            }
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void dragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xmouse ,y - ymouse);
    }//GEN-LAST:event_dragMouseDragged

    private void dragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMousePressed
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_dragMousePressed

    private void txt_pass2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pass2KeyReleased
        if(txt_pass1.getText().equals(txt_pass2.getText())){
            display.setText("Password Match");
            display.setForeground(Color.green);
        } else{
            display.setText("INVALID PASSWORD!");
            display.setForeground(Color.red);
        }
    }//GEN-LAST:event_txt_pass2KeyReleased

    private void btn_submitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submitMouseEntered
        btn_submit.setBackground(new Color(255,255,102));
    }//GEN-LAST:event_btn_submitMouseEntered

    private void btn_submitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submitMouseExited
        btn_submit.setBackground(Color.white);
    }//GEN-LAST:event_btn_submitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Registration().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btn_submit;
    private javax.swing.ButtonGroup btng_sex;
    private javax.swing.JComboBox<String> cb_age;
    private javax.swing.JComboBox<String> cb_date;
    private javax.swing.JComboBox<String> cb_month;
    private javax.swing.JComboBox<String> cb_year;
    private javax.swing.JLabel display;
    private javax.swing.JPanel drag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl_FullName;
    private javax.swing.JLabel lbl_addFormat;
    private javax.swing.JLabel lbl_age;
    private javax.swing.JLabel lbl_contact;
    private javax.swing.JLabel lbl_datebirth;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_name1;
    private javax.swing.JLabel lbl_name2;
    private javax.swing.JLabel lbl_name3;
    private javax.swing.JLabel lbl_residence;
    private javax.swing.JLabel lbl_sex;
    private javax.swing.JPanel pnl_register;
    private javax.swing.JRadioButton rb_female;
    private javax.swing.JRadioButton rb_male;
    private javax.swing.JTextField txt_PersoalInfo;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_contactNo;
    private javax.swing.JTextField txt_emailAdd;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JTextField txt_mname;
    private javax.swing.JPasswordField txt_pass1;
    private javax.swing.JPasswordField txt_pass2;
    // End of variables declaration//GEN-END:variables
}
